name: Merge CI
on: [ pull_request ]
jobs:
  Test:
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest ]
    steps:
        - uses: actions/checkout@v2
        - run: echo "The Job was automatically triggered by a pull request event again."
        - run: echo "The Job was automatically triggered by a pull request event now."
        - run: python master.py